services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_utf8.sql:/docker-entrypoint-initdb.d/init.sql

  cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_analytics
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  postgres_data: